version: '3.8'

services:
  db:
    image: mysql:8.0.37
    container_name: algodaily-drf-db
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - alogdaily-drf-backend

  redis:
    container_name: algodaily-drf-redis
    image: redis:7.4.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alogdaily-drf-backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algodaily-drf-api
    restart: always
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - alogdaily-drf-backend

volumes:
  mysql_data:
  redis_data:

networks:
  alogdaily-drf-backend:
    name: alogdaily-drf-backend
    driver: bridge
